// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Content for ParkingAdvertisement documents
 */
interface ParkingadvertisementDocumentData {
  /**
   * Building field in *ParkingAdvertisement*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: parkingadvertisement.building
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  building: prismic.SelectField<
    'Строение 1' | 'Строение 2' | 'Строение 6' | 'Строение 7'
  >

  /**
   * Level field in *ParkingAdvertisement*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Этаж
   * - **Default Value**: -1 Этаж
   * - **API ID Path**: parkingadvertisement.level
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  level: prismic.SelectField<'-1 Этаж' | '-2 Этаж', 'filled'>

  /**
   * ParkingNumber field in *ParkingAdvertisement*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: parkingadvertisement.parkingnumber
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  parkingnumber: prismic.NumberField
}

/**
 * ParkingAdvertisement document from Prismic
 *
 * - **API ID**: `parkingadvertisement`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ParkingadvertisementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ParkingadvertisementDocumentData>,
    'parkingadvertisement',
    Lang
  >

export type AllDocumentTypes = ParkingadvertisementDocument

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RichTextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  'rich_text',
  RichTextSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ParkingadvertisementDocument,
      ParkingadvertisementDocumentData,
      AllDocumentTypes,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    }
  }
}
